/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import connectfourclient.Client;
import java.awt.Color;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author merve
 */
public class Game extends javax.swing.JFrame {
    //framedeki komponentlere erişim için satatik oyun değişkeni

    public static Game ThisGame;
    //ekrandaki resim değişimi için timer yerine thread
    public Thread tmr_slider;
    public Point locations[][];
    public int boardStates[][];
    static int myColumn = 0;
    int myRow = 0;
    int RivalColumn = 0;
    int RivalRow = 0;
    public Point myPoint, rivalPoint;
    public Color myColor, rivalColor;
    public int playerNum = 0;
    public int numberOfMove = 0;
    public int rivalTurn = 0;
    public int myTurn = 0;
    int a = 0;
    int b = 0;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        this.setTitle("Connect Four");
        ThisGame = this;
        locations = new Point[7][6];
        boardStates = new int[7][6];

        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 6; j++) {
                boardStates[i][j] = 0;
                Point p = new Point(242 + i * 92, 50 + j * 92);

                locations[i][j] = p;
                // System.out.println(locations[i][j]);
            }
        }

        tmr_slider = new Thread(() -> {
            //
            while (Client.socket.isConnected()) {
                try {
                    Thread.sleep(100);

                    if (playerNum == 1) {

//                        System.out.println("rival turn : " + rivalTurn);
//                        System.out.println("my turn: " + myTurn);
                        if (numberOfMove == 0) {
                            unlockTheButtons();
                        } else {
                            if (rivalTurn == 1) {
                                lockTheButtons();
                                b = 0;
                            } else if (rivalTurn == 0 && b == 0) {
                                b = 1;

                                movingCircle m = new movingCircle(rivalPoint, Color.blue);
                                m.setOpaque(false);
                                m.setVisible(true);
                                m.setSize(this.getWidth(), this.getHeight());
                                ThisGame.add(m);

                                unlockTheButtons();
                                System.out.println("player1 : " + isConnenctFour());
                            }

                        }
                    } else if (playerNum == 2) {

//                        System.out.println("rival turn : " + rivalTurn);
//                        System.out.println("my turn: " + myTurn);
                        if (numberOfMove == 0) {
                            lockTheButtons();
                        } else {
                            if (rivalTurn == 0 && a == 0) {
                                a = 1;

                                movingCircle m = new movingCircle(rivalPoint, Color.red);
                                m.setOpaque(false);
                                m.setVisible(true);
                                m.setSize(this.getWidth(), this.getHeight());
                                ThisGame.add(m);

                                unlockTheButtons();
                                System.out.println("player2 :" + isConnenctFour());

                            } else if (rivalTurn == 1) {
                                a = 0;
                                lockTheButtons();
                            }
                        }

                       
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        connect_button = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_rival_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button1.setBackground(new java.awt.Color(199, 199, 199));
        button1.setText("1");
        button1.setEnabled(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(199, 199, 199));
        button2.setText("2");
        button2.setEnabled(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(199, 199, 199));
        button3.setText("3");
        button3.setEnabled(false);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(199, 199, 199));
        button4.setText("4");
        button4.setEnabled(false);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(199, 199, 199));
        button5.setText("5");
        button5.setEnabled(false);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(199, 199, 199));
        button6.setText("6");
        button6.setEnabled(false);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(199, 199, 199));
        button7.setText("7");
        button7.setEnabled(false);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        connect_button.setBackground(new java.awt.Color(199, 199, 199));
        connect_button.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        connect_button.setForeground(new java.awt.Color(241, 114, 17));
        connect_button.setText("Connect");
        connect_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(233, 82, 22), 3, true));
        connect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_buttonActionPerformed(evt);
            }
        });

        txt_name.setBackground(new java.awt.Color(255, 250, 250));
        txt_name.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(241, 114, 17));
        txt_name.setText("Name");
        txt_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 76, 16), 3, true));

        txt_rival_name.setEditable(false);
        txt_rival_name.setBackground(new java.awt.Color(255, 250, 250));
        txt_rival_name.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txt_rival_name.setForeground(new java.awt.Color(69, 119, 129));
        txt_rival_name.setText("Rival Name");
        txt_rival_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(103, 211, 232), 3, true));
        txt_rival_name.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(199, 199, 199));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/board.png"))); // NOI18N
        jLabel1.setLabelFor(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(910, 910, 910)
                .addComponent(txt_rival_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(692, 692, 692)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(782, 782, 782)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(connect_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_rival_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(connect_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class movingCircle extends JPanel implements ActionListener {

        Timer t = new Timer(0, this);

        int x, y;
        double velX = 3, velY = 3;
        Color color;
        int finishPoint = 520;

        public movingCircle(Point p, Color c) {
            x = (int) p.getX() - 15;
            y = 40;
            finishPoint = (int) p.getY() - 10;
            color = c;
        }

        public void paint(Graphics g) {
            super.paint(g);
            Graphics2D g2 = (Graphics2D) g;
            g2.clearRect(x, y, 60, 60);
            Ellipse2D circle = new Ellipse2D.Double(x, y, 70, 70);
            g.setColor(color);
            g2.fill(circle);
            t.start();
        }

        @Override
        public void actionPerformed(ActionEvent e) {

            if (y <= finishPoint) {
                repaint();
                y += velY;
            }

        }

    }

    public boolean isPlayable(int column) {
        return boardStates[column][0] == 0;
    }

    void lockTheButtons() {
        Game.ThisGame.button1.setEnabled(false);
        Game.ThisGame.button2.setEnabled(false);
        Game.ThisGame.button3.setEnabled(false);
        Game.ThisGame.button4.setEnabled(false);
        Game.ThisGame.button5.setEnabled(false);
        Game.ThisGame.button6.setEnabled(false);
        Game.ThisGame.button7.setEnabled(false);
    }

    void unlockTheButtons() {
        Game.ThisGame.button1.setEnabled(true);
        Game.ThisGame.button2.setEnabled(true);
        Game.ThisGame.button3.setEnabled(true);
        Game.ThisGame.button4.setEnabled(true);
        Game.ThisGame.button5.setEnabled(true);
        Game.ThisGame.button6.setEnabled(true);
        Game.ThisGame.button7.setEnabled(true);
    }

    public void drawTheMove(int myColumn) {

        for (int i = 5; i >= 0; i--) {
            if (boardStates[myColumn][i] == 0) {
                myRow = i;
                break;
            }
        }
        boardStates[myColumn][myRow] = playerNum;

        movingCircle m = new movingCircle(locations[myColumn][myRow], myColor);
        m.setOpaque(false);
        m.setVisible(true);
        m.setSize(this.getWidth(), this.getHeight());

        ThisGame.add(m);
        myPoint = locations[myColumn][myRow];
        numberOfMove++;
        myTurn = 0;
        rivalTurn = 1;
    }

    public void sendMessagesToRival() {
        Message msg = new Message(Message.Message_Type.Board);
        msg.content = boardStates;
        Client.Send(msg);

        Message msg2 = new Message(Message.Message_Type.Point);
        msg2.content = myPoint;
        Client.Send(msg2);

        Message msg3 = new Message(Message.Message_Type.Move);
        msg3.content = numberOfMove;
        Client.Send(msg3);

        Message msg4 = new Message(Message.Message_Type.Turn);
        msg4.content = myTurn;
        Client.Send(msg4);
    }

    public boolean isConnenctFour() {
        int value = boardStates[myColumn][myRow];
        int counter = 0;
        int i = myRow;
        int j = myColumn;

        //dikey kontrol
        while (i < 6 && boardStates[myColumn][i] == value) {
            counter++;
            i++;
        }
        if (counter == 4) {
            return true;
        }
        //yatay kontrol
        counter = 0;
        while (j < 7 && boardStates[j][myRow] == value) {
            counter++;
            j++;
        }
        j = myColumn - 1;
        while (j >= 0 && boardStates[j][myRow] == value) {
            counter++;
            j--;
        }
        if (counter == 4) {
            return true;
        }
        //capraz1 kontrol
        j = myColumn;
        i = myRow;
        counter = 0;
        while (j < 7 && i < 6 && boardStates[j][i] == value) {
            counter++;
            i++;
            j++;
        }
        j = myColumn -1;
        i = myRow -1;
        while(j>=0 && i>=0 && boardStates[j][i] == value ){
           counter++;
           i--;
           j--;
        }
        if(counter == 4){
           return true;
        }
        
       //capraz2 kontrol
       counter = 0;
       j = myColumn;
       i = myRow;
       while(j<7 && i>=0 && boardStates[j][i] == value){
         counter++;
         j++;
         i--;
       }
       j = myColumn-1;
       i = myRow+1;
       while(i<6 && j>=0 && boardStates[j][i] == value) {
         counter++;
         j--;
         i++;
       }
       if(counter == 4){
           return true;
       }
        return false;

    }
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        myColumn = 0;

        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();

        } else {
            //this column is full, try another one

        }


    }//GEN-LAST:event_button1ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        myColumn = 3;
        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();
        } else {
            //this column is full, try another one
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        myColumn = 2;

        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();
        } else {
            //this column is full, try another one
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void connect_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_buttonActionPerformed
        Client.Start("127.0.0.1", 2000);

        connect_button.setEnabled(false);
        txt_name.setEnabled(false);


    }//GEN-LAST:event_connect_buttonActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        myColumn = 1;

        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();
        } else {
            //this column is full, try another one
        }

    }//GEN-LAST:event_button2ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        myColumn = 4;

        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();
        } else {
            //this column is full, try another one
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        myColumn = 5;

        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();
        } else {
            //this column is full, try another one
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        myColumn = 6;

        if (isPlayable(myColumn)) {
            drawTheMove(myColumn);
            sendMessagesToRival();
        } else {
            //this column is full, try another one
        }
    }//GEN-LAST:event_button7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton button1;
    public javax.swing.JButton button2;
    public javax.swing.JButton button3;
    public javax.swing.JButton button4;
    public javax.swing.JButton button5;
    public javax.swing.JButton button6;
    public javax.swing.JButton button7;
    public javax.swing.JButton connect_button;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField txt_name;
    public javax.swing.JTextField txt_rival_name;
    // End of variables declaration//GEN-END:variables
}
